name: Tests on Linux GPU (Gym)

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  unittests:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      repository: pytorch/rl
      runner: "linux.g5.4xlarge.nvidia.gpu"
      gpu-arch-type: "cuda"
      gpu-arch-version: "11.6"
      timeout: 120
      script: |
        set -euxo pipefail
        export PYTHON_VERSION="3.8"
        export CU_VERSION="${{ inputs.gpu-arch-version }}"
        ./.circleci/unittest/linux_libs/scripts_gym/setup_env.sh
        ./.circleci/unittest/linux_libs/scripts_gym/batch_scripts.sh
        ./.circleci/unittest/linux_libs/scripts_gym/post_process.sh
