name: Unit-tests on Windows GPU

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  unittests:
    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
    with:
      runner: "windows.8xlarge.nvidia.gpu"
      repository: pytorch/rl
      timeout: 240
      script: |
        set -euxo pipefail

        export PYTHON_VERSION="3.9"
        export CUDA_VERSION="11.6"

        # TODO: Port this to pytorch/test-infra/.github/workflows/windows_job.yml
        export PATH="/c/Jenkins/Miniconda3/Scripts:${PATH}"

        echo "PYTHON_VERSION: $PYTHON_VERSION"
        echo "CU_VERSION: $CU_VERSION"
        
        ## setup_env.sh
        ./.circleci/unittest/windows_optdepts/scripts/setup_env.sh

        ## install.sh
        ./.circleci/unittest/windows_optdepts/scripts/install.sh

        ## run_test.sh
        ./.circleci/unittest/windows_optdepts/scripts/run_test.sh

        ## post_process.sh
        ./.circleci/unittest/windows_optdepts/scripts/post_process.sh
